platform: "stm32f4"
ram_size: "192KB"
flash_size: "1MB"
stack_size: "8KB"
heap_size: "16KB"
max_interrupt_latency: "100us"

safety_level: "IEC61508-SIL2"
critical_functions:
  - "plan"
  - "moveObstacle"
  - "addDynamicObstacle"
